### PR TITLE
Update docs theme to fix the tox build.

### PR DESCRIPTION
**Pull request by ryneeverett**

### CODE REVIEW

**Comment by Ivoz** [comment]
Seems this isn't needed any more. Cheers

**Comment by ryneeverett** [comment]
@Ivoz Perhaps the've implemented a deprecation grace period but you're still using an undocumented setting value that will no doubt break the build again some day.

**Comment by Ivoz** [comment]
https://github.com/pypa/scripttest/blob/b7ffd78b460363f7b0dcbaa020b7eb87aee8b952/docs/conf.py#L103

**Comment by ryneeverett** [comment]
Cool.

**Pull request closed without merging**
