### PR TITLE
Prevent named pipes from blocking indefinitely.

### PR DESCRIPTION
**Pull request by ryneeverett**
See http://stackoverflow.com/questions/5782279/why-does-a-read-only-open-of-a-named-pipe-block.

### CODE REVIEW

**Comment by Ivoz** [comment]
Could you give a specific example of something this fixes?

**Comment by ryneeverett** [comment]
@Ivoz I believe scripttest, when iterating over the contents to detect changes, will block indefinitely on any named pipe in the `TestFileEnvironment`'s path. That's because, as the above link explains, named pipes can't be opened (at the C level). Since pipes have no content -- they're not *really* files -- I assign a content of `None`, which will show no change if it still exists after the `run` since `bool(None==None) == True`.

**Comment by ryneeverett** [comment]
@Ivoz The specific example / use case is that the script under test left a named pipe in the path, which caused scripttest to block indefinitely when calculating `files_after`. My solution was to make sure I was removing the named pipe in my script, which was what I should have been doing anyway.

I'll admit that leaving named pipes sitting around is probably never good practice, but blocking forever doesn't seem like a reasonable response (and isn't that easy to debug unless you're already aware of the blocking behavior).

**Comment by chrahunt** [comment]
Thanks @ryneeverett!

**Pull request merged**
